#ifndef GLOBALtype
#define GLOBALtype( type)
#endif

#ifndef GLOBALname
#define GLOBALname( name)
#endif

#ifndef GLOBALinit
#define GLOBALinit( init)
#endif


#define GLOBAL( type, name, init) GLOBALtype(type) GLOBALname(name) GLOBALinit(init)


/*
 * CiviCC specific global variables
 */

GLOBAL( char*, includedir, NULL)
GLOBAL( bool, preprocessor_enabled, FALSE)

#undef GLOBALtype
#undef GLOBALname
#undef GLOBALinit
#undef GLOBAL


